### PR TITLE
add an extra function to specify the I2C bus

### PR DESCRIPTION
**Pull request by crazystick**
The I2C bus appears as /dev/i2c-2 on the HB i2eX under ArchLinuxArm - I don't know if it can appear as /dev/i2c-0 on some other devices, so the original behaviour is maintained, with an additional function int wiringHBI2CSetupB(int devId, int busId) if you need a different bus number

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Is it possible to somehow determine what i2c device we should use?

**Comment by crazystick** [comment]
I'm not too sure. device numbering is determined by the kernel. In the dtsi file i2c1 and i2c2 are defined, see https://github.com/SolidRun/linux-imx6-3.14/blob/linux-linaro-lsk-v3.14-mx6/arch/arm/boot/dts/imx6qdl-hummingboard.dtsi and I had to add i2c3 for the i2c bus on the header. I hope SR will add it to their kernel, and possibly the numbers in the dtsi correspond to the numbers assigned by the kernel - they do on my board. However I don't have any other OS to test that.

**Comment by CurlyMoo** [comment]
Is it possible to poll the i2c ports to see which one is active?

**Comment by crazystick** [comment]
Well we don't know what might be connected on the i2c bus in order to poll it. We know what is on the other two busses on the pro carrier, but I'm not sure it would be safe to access them. Maybe we should ask SR. The RPi code just assumes the number based on the board version, and I assumed that you had bus 0 because that is where it showed up for you.

I tried making some more modifications to the dtsi file this morning, but I didn't reach any definite conclusion. For me, it always appeared on bus 2, although I did manage to move other things.

**Comment by CurlyMoo** [comment]
Sadly, i can only add a definitive solution when we have answers....

**Comment by crazystick** [comment]
I got an email from @rabeeh at SR - hopefully he will be able to give us some more information end of next week, in addition to pulling the necessary changes into the SolidRun kernel

**Comment by crazystick** [comment]
I guess wiringHB is dead, in favour of wiringX

**Pull request closed without merging**
